version: "3"
services:
    webserver:
        build:
            context: ./bin/php/${PHP_VERSION}
        container_name: '${PROJECT_NAME}-${PHP_VERSION}'
        restart: 'always'
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        links:
            - database
        volumes:
            - ${DOCUMENT_ROOT:-./www}:/var/www/html
            - ${PHP_INI:-./config/php/php.ini}:/usr/local/etc/php/php.ini
            - ${VHOSTS_DIR:-./config/vhosts}:/etc/apache2/sites-enabled
            - ${APACHE_LOG_DIR:-./logs/apache2}:/var/log/apache2
        environment:
            APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
            PMA_PORT: ${PMA_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    database:
        build:
            context: ./bin/db/${DATABASE}
        container_name: '${PROJECT_NAME}-db-${DATABASE}'
        restart: 'always'
        ports:
            - "127.0.0.1:${MYSQL_PORT}:3306"
        volumes:
            - ${MYSQL_DATA_DIR:-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR:-./logs/mysql}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: '${PROJECT_NAME}-phpmyadmin'
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        ports:
            - '${PMA_PORT}:80'
        volumes:
            - /sessions
            - ${PHP_INI:-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
